// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v3.12.4
// source: do_task.proto

package users_service

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	TodoTaskService_Create_FullMethodName  = "/users_service.TodoTaskService/Create"
	TodoTaskService_GetById_FullMethodName = "/users_service.TodoTaskService/GetById"
	TodoTaskService_GetList_FullMethodName = "/users_service.TodoTaskService/GetList"
	TodoTaskService_Update_FullMethodName  = "/users_service.TodoTaskService/Update"
	TodoTaskService_Delete_FullMethodName  = "/users_service.TodoTaskService/Delete"
)

// TodoTaskServiceClient is the client API for TodoTaskService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TodoTaskServiceClient interface {
	Create(ctx context.Context, in *CreateDoTask, opts ...grpc.CallOption) (*DoTask, error)
	GetById(ctx context.Context, in *DoTaskPrimaryKey, opts ...grpc.CallOption) (*DoTask, error)
	GetList(ctx context.Context, in *GetListDoTaskRequest, opts ...grpc.CallOption) (*GetListDoTaskResponse, error)
	Update(ctx context.Context, in *UpdateDoTask, opts ...grpc.CallOption) (*DoTask, error)
	Delete(ctx context.Context, in *DoTaskPrimaryKey, opts ...grpc.CallOption) (*Empty, error)
}

type todoTaskServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTodoTaskServiceClient(cc grpc.ClientConnInterface) TodoTaskServiceClient {
	return &todoTaskServiceClient{cc}
}

func (c *todoTaskServiceClient) Create(ctx context.Context, in *CreateDoTask, opts ...grpc.CallOption) (*DoTask, error) {
	out := new(DoTask)
	err := c.cc.Invoke(ctx, TodoTaskService_Create_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *todoTaskServiceClient) GetById(ctx context.Context, in *DoTaskPrimaryKey, opts ...grpc.CallOption) (*DoTask, error) {
	out := new(DoTask)
	err := c.cc.Invoke(ctx, TodoTaskService_GetById_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *todoTaskServiceClient) GetList(ctx context.Context, in *GetListDoTaskRequest, opts ...grpc.CallOption) (*GetListDoTaskResponse, error) {
	out := new(GetListDoTaskResponse)
	err := c.cc.Invoke(ctx, TodoTaskService_GetList_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *todoTaskServiceClient) Update(ctx context.Context, in *UpdateDoTask, opts ...grpc.CallOption) (*DoTask, error) {
	out := new(DoTask)
	err := c.cc.Invoke(ctx, TodoTaskService_Update_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *todoTaskServiceClient) Delete(ctx context.Context, in *DoTaskPrimaryKey, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, TodoTaskService_Delete_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TodoTaskServiceServer is the server API for TodoTaskService service.
// All implementations must embed UnimplementedTodoTaskServiceServer
// for forward compatibility
type TodoTaskServiceServer interface {
	Create(context.Context, *CreateDoTask) (*DoTask, error)
	GetById(context.Context, *DoTaskPrimaryKey) (*DoTask, error)
	GetList(context.Context, *GetListDoTaskRequest) (*GetListDoTaskResponse, error)
	Update(context.Context, *UpdateDoTask) (*DoTask, error)
	Delete(context.Context, *DoTaskPrimaryKey) (*Empty, error)
	mustEmbedUnimplementedTodoTaskServiceServer()
}

// UnimplementedTodoTaskServiceServer must be embedded to have forward compatible implementations.
type UnimplementedTodoTaskServiceServer struct {
}

func (UnimplementedTodoTaskServiceServer) Create(context.Context, *CreateDoTask) (*DoTask, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Create not implemented")
}
func (UnimplementedTodoTaskServiceServer) GetById(context.Context, *DoTaskPrimaryKey) (*DoTask, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetById not implemented")
}
func (UnimplementedTodoTaskServiceServer) GetList(context.Context, *GetListDoTaskRequest) (*GetListDoTaskResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetList not implemented")
}
func (UnimplementedTodoTaskServiceServer) Update(context.Context, *UpdateDoTask) (*DoTask, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Update not implemented")
}
func (UnimplementedTodoTaskServiceServer) Delete(context.Context, *DoTaskPrimaryKey) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Delete not implemented")
}
func (UnimplementedTodoTaskServiceServer) mustEmbedUnimplementedTodoTaskServiceServer() {}

// UnsafeTodoTaskServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TodoTaskServiceServer will
// result in compilation errors.
type UnsafeTodoTaskServiceServer interface {
	mustEmbedUnimplementedTodoTaskServiceServer()
}

func RegisterTodoTaskServiceServer(s grpc.ServiceRegistrar, srv TodoTaskServiceServer) {
	s.RegisterService(&TodoTaskService_ServiceDesc, srv)
}

func _TodoTaskService_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateDoTask)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TodoTaskServiceServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TodoTaskService_Create_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TodoTaskServiceServer).Create(ctx, req.(*CreateDoTask))
	}
	return interceptor(ctx, in, info, handler)
}

func _TodoTaskService_GetById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DoTaskPrimaryKey)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TodoTaskServiceServer).GetById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TodoTaskService_GetById_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TodoTaskServiceServer).GetById(ctx, req.(*DoTaskPrimaryKey))
	}
	return interceptor(ctx, in, info, handler)
}

func _TodoTaskService_GetList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetListDoTaskRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TodoTaskServiceServer).GetList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TodoTaskService_GetList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TodoTaskServiceServer).GetList(ctx, req.(*GetListDoTaskRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TodoTaskService_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateDoTask)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TodoTaskServiceServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TodoTaskService_Update_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TodoTaskServiceServer).Update(ctx, req.(*UpdateDoTask))
	}
	return interceptor(ctx, in, info, handler)
}

func _TodoTaskService_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DoTaskPrimaryKey)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TodoTaskServiceServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TodoTaskService_Delete_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TodoTaskServiceServer).Delete(ctx, req.(*DoTaskPrimaryKey))
	}
	return interceptor(ctx, in, info, handler)
}

// TodoTaskService_ServiceDesc is the grpc.ServiceDesc for TodoTaskService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TodoTaskService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "users_service.TodoTaskService",
	HandlerType: (*TodoTaskServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _TodoTaskService_Create_Handler,
		},
		{
			MethodName: "GetById",
			Handler:    _TodoTaskService_GetById_Handler,
		},
		{
			MethodName: "GetList",
			Handler:    _TodoTaskService_GetList_Handler,
		},
		{
			MethodName: "Update",
			Handler:    _TodoTaskService_Update_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _TodoTaskService_Delete_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "do_task.proto",
}
